# Cloudflare Pages deployment configuration
name = "vault"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

# Compatibility flags
compatibility_flags = ["nodejs_compat"]

# Environment variables will be set in Cloudflare Pages dashboard:
# - DATABASE_URL (set in dashboard)
# - NEXT_PUBLIC_WORKER_URL (set in dashboard)
