# Cloudflare Pages deployment configuration
# This file is for reference - Cloudflare Pages uses build settings from the dashboard

name = "vault-frontend"
compatibility_date = "2024-01-01"

# Pages routes are handled by Next.js App Router
# No additional routes configuration needed

# Environment variables (set in Cloudflare Pages dashboard)
# NEXT_PUBLIC_WORKER_URL = "https://vault-api.yourdomain.workers.dev"

# Build settings for Cloudflare Pages:
# - Build command: npm run pages:build
# - Build output directory: .vercel/output/static
# - Framework preset: Next.js
# - Node version: 18+

# For the Worker API (vault-api), use a separate wrangler.toml:
# ---
# name = "vault-api"
# main = "src/index.ts"
# compatibility_date = "2024-01-01"
#
# [[r2_buckets]]
# binding = "VAULT_DATA"
# bucket_name = "vault-data"
# preview_bucket_name = "vault-data-preview"
#
# [vars]
# ALLOWED_ORIGINS = "https://vault.yourdomain.com,http://localhost:3000"
